<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <RepositoryUrl>https://github.com/nscript-site/NewBeeVG</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageId>NewBeeVG.ThreeD</PackageId>
    <PackageTags>avalonia,NewBeeVG</PackageTags>
    <PackageProjectUrl>https://github.com/nscript-site/NewBeeVG</PackageProjectUrl>
    <Copyright>geblab.com</Copyright>
    <Title>NewBeeVG ThreeD: An 3d extention for NewBeeVG</Title>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <IncludeSymbols>False</IncludeSymbols>
    <Company>geblab</Company>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <PackageReadmeFile>3d.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\docs\3d.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\3rd\helix-toolkit-nex\Source\HelixToolkit-Nex\HelixToolkit.Nex.Engine\HelixToolkit.Nex.Engine.csproj" />
    <ProjectReference Include="..\..\3rd\helix-toolkit-nex\Source\HelixToolkit-Nex\HelixToolkit.Nex.Graphics.Vulkan\HelixToolkit.Nex.Graphics.Vulkan.csproj" />
    <ProjectReference Include="..\..\3rd\helix-toolkit-nex\Source\HelixToolkit-Nex\HelixToolkit.Nex\HelixToolkit.Nex.csproj" />
    <ProjectReference Include="..\NewBeeVG\NewBeeVG.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
</Project>
