namespace NewBeeMedia.Subtitles;

/// <summary>
/// 字幕导出器
/// </summary>
public class SubExporter
{
    private String _softwareName;
    private int _frameWidth;
    private int _frameHeight;
    private MediaSubtitles _subtitles;
    private ContentFlag[] _langFlags;
    private SubtitleStyle _style;

    public SubExporter(String softwareName, MediaSubtitles subtitles, SubtitleStyle style, int frameWidth, int frameHeight, ContentFlag[] langFlags)
    {
        this._subtitles = subtitles;
        this._softwareName = softwareName;
        this._frameWidth = frameWidth;
        this._frameHeight = frameHeight;
        this._langFlags = langFlags;
        this._style = style;
    }

    //private string GetAssCnText(string ch)
    //{
    //    if (String.IsNullOrEmpty(ch)) return String.Empty;

    //    try
    //    {

    //        StringBuilder sb = new StringBuilder();

    //        if (_style == null)
    //        {
    //            int max = 30;
    //            int len = ch.Length;
    //            int count = (len + max - 1) / max;
    //            string[] strs = new string[count];
    //            for (int i = 0; i < count; i++)
    //            {
    //                int beginIndex = i * max;
    //                int endIndex = (i + 1) * max;
    //                int subLen = endIndex > len ? len - beginIndex : max;
    //                strs[i] = ch.Substring(beginIndex, subLen);
    //            }

    //            foreach (var subString in strs)
    //            {
    //                sb.AppendLine(subString);
    //            }
    //        }
    //        else
    //        {
    //            var fontName = _style.FontName;
    //            var fontSize = _style.FontSize;
    //            int index = 0;
    //            var oriStr = ch;

    //            StringFormat stringFormat = new StringFormat();
    //            Font font = new Font(fontName, fontSize, GraphicsUnit.Pixel);
    //            var height = font.GetHeight();
    //            using (Bitmap bmp = new Bitmap(_frameWidth, _frameHeight))
    //            {
    //                using (Graphics g = Graphics.FromImage(bmp))
    //                {
    //                    while (index < oriStr.Length)
    //                    {
    //                        g.MeasureString(ch, font, new SizeF(_frameWidth, height), stringFormat, out int fitted, out int lines);
    //                        var subItem = oriStr.Substring(index, fitted);
    //                        sb.AppendLine(subItem);
    //                        ch = oriStr.Substring(index + fitted);
    //                        index += fitted;
    //                    }
    //                    if (index < oriStr.Length)
    //                    {
    //                        var subItem = oriStr.Substring(index, oriStr.Length - index);
    //                        sb.AppendLine(subItem);
    //                    }
    //                }
    //            }
    //        }
    //        return sb.ToString();
    //    }
    //    catch (Exception ex)
    //    {
    //        ch += "[Exception]";
    //        ch += ex.Message;
    //        ch += ex.StackTrace;
    //        //Console.WriteLine(ex.Message);
    //        //Console.WriteLine(ex.StackTrace);
    //    }

    //    return ch;
    //}

    public String ExportAss()
    {
        StringBuilder sbFull = new StringBuilder();
        StringBuilder sbStyles = new StringBuilder();
        StringBuilder sbEvents = new StringBuilder();

        WriteScriptInfo(sbFull);
        WriteDefaultStyle(sbStyles);
        WriteEventsHeader(sbEvents);

        if (_subtitles != null)
        {
            foreach (var subData in _subtitles)
            {
                WriteEvents(subData, _style, sbEvents, sbStyles);
            }
        }

        sbFull.AppendLine();
        sbFull.Append(sbStyles.ToString());
        sbFull.AppendLine();
        sbFull.Append(sbEvents.ToString());

        return sbFull.ToString();
    }

    private void WriteScriptInfo(StringBuilder sb)
    {
        sb.AppendLine("[Script Info]");
        if (_softwareName != null)
            sb.AppendLine("; Script generated by " + _softwareName);
        sb.AppendLine("ScriptType: v4.00+");
        if (_frameWidth > 0 && _frameHeight > 0)
        {
            sb.AppendLine("PlayResX: " + _frameWidth.ToString());
            sb.AppendLine("PlayResY: " + _frameHeight.ToString());
        }
        sb.AppendLine("Timer: 100.0000");
        sb.AppendLine("WrapStyle: 0");
        sb.AppendLine("ScaledBorderAndShadow: no");
    }

    private void WriteEvents(MediaSubtitleItem sub, SubtitleStyle style, StringBuilder sbEvents, StringBuilder sbStyles)
    {
        String styleName = DefaultStyleName;

        if (style != null)
        {
            // 添加自定义的style
            styleName = GetNextCustomStyleName();
            WriteStyle(style, styleName, sbStyles);
        }

        String caption = GetText(sub);

        if (caption == null) caption = String.Empty;

        caption = caption.Replace("\n", "\\N");
        caption = caption.Replace("\r", "");

        sbEvents.AppendLine(String.Format(
            "Dialogue: 0,{0},{1},{2},,0,0,0,,{3}",
            FormatTime(sub.Start), FormatTime(sub.End), styleName, caption)
        );
    }

    private String FormatTime(double time)
    {
        int hours = (int)(time / 3600);
        time -= hours * 3600;
        int mins = (int)(time / 60);
        time -= mins * 60;
        int seconds = (int)(time);
        time -= seconds;
        int ms = (int)(time * 100);
        return String.Format("{0}:{1}:{2}.{3}", FormatNum(hours, 1), FormatNum(mins, 2), FormatNum(seconds, 2), FormatNum(ms, 2));
    }

    private String FormatNum(int num, int length)
    {
        String result = num.ToString();
        while (result.Length < length)
        {
            result = "0" + result;
        }
        return result;
    }

    //private String Filter(ContentFlag flag, String txt)
    //{
    //    if(flag == ContentFlag.LANG_ZH && txt != null)
    //    {
    //        return this.GetAssCnText(txt);
    //    }
    //    return txt;
    //}

    private String GetText(MediaSubtitleItem sub)
    {
        String txt = sub.ToText(_langFlags);
        StringBuilder sb = new StringBuilder();
        if (txt != null)
        {
            foreach (Char c in txt)
            {
                sb.Append(c).Append("");
            }
        }
        return sb.ToString();
    }

    private void WriteEventsHeader(StringBuilder sb)
    {
        sb.AppendLine("[Events]");
        sb.AppendLine("Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text");
    }

    private static String DefaultStyleName = "Default";

    private int _customStyleId = 0;
    private String GetNextCustomStyleName()
    {
        _customStyleId++;
        return "CS" + _customStyleId;
    }

    private void WriteDefaultStyle(StringBuilder sb)
    {
        SubtitleStyle defaultStyle = SubtitleStyle.DefaultStyle;
        sb.AppendLine("[V4+ Styles]");
        sb.AppendLine("Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding");
        sb.AppendLine(ToStyleText(defaultStyle, DefaultStyleName));
    }

    private void WriteStyle(SubtitleStyle style, String styleName, StringBuilder sb)
    {
        if (style == null) return;
        sb.AppendLine(ToStyleText(style, styleName));
    }

    // Style: zs,微软雅黑,16,&H00FFFFFF,&H0000FFFF,&H00000000,&H80000000,-1,0,0,0,100,100,1,0,1,2,0,2,20,20,70,1
    private String ToStyleText(SubtitleStyle style, String styleName)
    {
        return String.Format("Style: {0},{1},{2}," +    // Name, Fontname, Fontsize
            "{3},{4},{5},{6}," +                        // PrimaryColour, SecondaryColour, OutlineColour, BackColour
            "{7},{8},{9},{10}," +                       // Bold, Italic, Underline, StrikeOut
            "{11},{12}," +                              // ScaleX, ScaleY
            "{13},{14},{15},{16},{17}," +               // Spacing, Angle, BorderStyle, Outline, Shadow
            "{18},{19},{20},{21},{22}",                 // Alignment, MarginL, MarginR, MarginV, Encoding
            styleName, style.FontName, style.FontSize.ToString("0.0000"),
            ToColor(style.FontColor), ToColor(style.FontColor), ToColor(style.BorderColor), "&H00000000",
            "0", "0", "0", "0",
            "100", "100",
            "0", "0", "1", ToOutline(style), "0",
            ToAlignment(style), ToMarginL(style), ToMarginR(style), ToMarginV(style),
            "134"
            );
    }

    private String ToOutline(SubtitleStyle style)
    {
        return ((int)Math.Round(style.BorderThickness / 2.0)).ToString();
    }

    private String ToMarginL(SubtitleStyle style)
    {
        return ((int)Math.Round(style.HSafeMargin)).ToString();
    }

    private String ToMarginR(SubtitleStyle style)
    {
        return ((int)Math.Round(style.HSafeMargin)).ToString();
    }

    private String ToMarginV(SubtitleStyle style)
    {
        return ((int)Math.Round(style.VSafeMargin)).ToString();
    }

    private String ToAlignment(SubtitleStyle style)
    {
        String align = "2";
        switch (style.FontAlign)
        {
            case "left":
            case "Left":
                align = "1";
                break;
            case "right":
            case "Right":
                align = "3";
                break;
        }
        return align;
    }

    private String ToColor(int color)
    {
        System.Drawing.Color c = System.Drawing.Color.FromArgb(color);
        return "&H00" + ToHex(c.B) + ToHex(c.G) + ToHex(c.R);
    }

    private String ToHex(byte val)
    {
        return Convert.ToString(val, 16).ToUpper().PadLeft(2, '0');
    }
}
