<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <Version>1.0.1.1</Version>
    <RepositoryUrl>https://github.com/nscript-site/NewBeeVG</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageId>NewBeeVG</PackageId>
    <PackageTags>avalonia,NewBeeVG</PackageTags>
    <PackageProjectUrl>https://github.com/nscript-site/NewBeeVG</PackageProjectUrl>
    <Copyright>geblab.com</Copyright>
    <Title>NewBeeVG: An AI coding-powered tool for fast procedural animation and video creation</Title>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <IncludeSymbols>False</IncludeSymbols>
    <Company>geblab</Company>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>

  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <!--<PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" />-->
    <PackageReference Include="NAudio" />
    <PackageReference Include="newbeeui" />
    <PackageReference Include="pythonnet" />
    <PackageReference Include="SkiaSharp.Skottie" />
    <PackageReference Include="Svg.Skia" />
    <PackageReference Include="TypstNET" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NewBeeMedia" />
    <!--<ProjectReference Include="..\NewBeeMedia\NewBeeMedia.csproj" />-->
  </ItemGroup>

</Project>
