global using Avalonia;
global using Avalonia.Controls;
global using Avalonia.Layout;
global using Avalonia.Markup.Declarative;
global using Avalonia.Media;
global using NStyles;
global using NewBeeUI;
global using NewBeeVG;
global using static NewBeeVG.Methods;
global using NStyles.MeterialIcons;
global using System.Collections.Generic;
global using System;
global using NewBeeVG.Viewer.Widgets;
global using NewBeeVG.Viewer;
